$('.owl-one').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1       
         },
        1000:{
            items:1
        }
    }
})

$('.owl-two').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3      
         },
        1000:{
            items:3
        }
    }
})

$(".hamburger").click(function(){
    $(".hamburgerCLICK").toggle();
  });